site:
    name: Caremad
    url: "https://caremad.io/"

config:
    source: content
    output: deploy
    static: deploy/static
    static_prefix: /static/
    permalink: "blog/{{filename}}/"
    relative_url: false
    perpage: 10000000000000000000000000
    feedcount: 20
    timezone: "-05:00"

author:
    default: dstufft

reader:
    active:
        - liquidluck.readers.markdown.MarkdownReader

writer:
    active:
        - custom.writers.PostWriter
        - custom.writers.PageWriter
        - liquidluck.writers.core.ArchiveWriter
        - liquidluck.writers.core.ArchiveFeedWriter
        - liquidluck.writers.core.FileWriter
        - liquidluck.writers.core.StaticWriter
        #- liquidluck.writers.core.YearWriter
        #- liquidluck.writers.core.CategoryWriter
        #- liquidluck.writers.core.CategoryFeedWriter
        #- liquidluck.writers.core.TagWriter
        #- liquidluck.writers.core.TagCloudWriter
    vars:
        # uncomment if you want to reset archive page
        # archive_output: archive.html

theme:
    name: caremad

    # theme variables are defined by theme creator
    # you can access theme in template with ``theme`` namespace
    # for instance: {{theme.disqus}}
    vars:
        projects:
            - - Warehouse
              - "https://github.com/pypa/warehouse"
              - Next Generation Python Package Index
            - - pip
              - "https://github.com/pypa/pip"
              - The standard Python package installer
            - - twine
              - "https://github.com/dstufft/twine"
              - Utilities for interacting with PyPI
            - - PyNaCl
              - "https://github.com/pyca/pynacl"
              - Python binding to the Networking and Cryptography (NaCl) library
            - - bcrypt
              - "https://github.com/pyca/bcrypt"
              - Modern password hashing for your software and your servers
            - - Cryptography
              - "https://github.com/pyca/cryptography"
              - Cryptographic primitives and recipes in Python

template:
    vars:
        # key: value
    filters:
        # key: value
